kind: Secret
apiVersion: v1
metadata:
  name: customerllm-env
  namespace: scalovate-qpp-redhat-poc #change this
  uid: a93b67c3-969d-48c7-a57d-5af4de263484 #change this
  resourceVersion: "4524229"
  creationTimestamp: "2026-01-11T22:33:00Z"
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"API_VERSION":"djE=","APP_ENV":"cHJvZHVjdGlvbg==","APP_NAME":"Q3VzdG9tZXJMTE0=","BACKEND_HOST":"MC4wLjAuMA==","BACKEND_PORT":"ODAwMA==","BACKEND_URL":"aHR0cHM6Ly9jdXN0b21lcmxsbS1iYWNrZW5kLXNjYWxvdmF0ZS1xcHAtcmVkaGF0LXBvYy5hcHBzLmNsdXN0ZXItNHp4cWIuNHp4cWIuc2FuZGJveDEzNC5vcGVudGxjLmNvbQ==","CORS_ORIGINS":"aHR0cHM6Ly9jdXN0b21lcmxsbS1mcm9udGVuZC1zY2Fsb3ZhdGUtcXBwLXJlZGhhdC1wb2MuYXBwcy5jbHVzdGVyLTR6eHFiLjR6eHFiLnNhbmRib3gxMzQub3BlbnRsYy5jb20=","DATABASE_URL":"cG9zdGdyZXNxbDovL2N1c3RvbWVybGxtOmNoYW5nZW1lX3NlY3VyZV9wYXNzd29yZEBwb3N0Z3Jlczo1NDMyL2N1c3RvbWVybGxt","DEBUG":"ZmFsc2U=","EMBEDDINGS_PROVIDER":"dGVp","FILE_STORAGE_PATH":"L2RhdGE=","FRONTEND_URL":"aHR0cHM6Ly9jdXN0b21lcmxsbS1mcm9udGVuZC1zY2Fsb3ZhdGUtcXBwLXJlZGhhdC1wb2MuYXBwcy5jbHVzdGVyLTR6eHFiLjR6eHFiLnNhbmRib3gxMzQub3BlbnRsYy5jb20=","OCR_LLM_CORRECTION_ENABLED":"dHJ1ZQ==","OCR_WORKER_PORT":"ODAwMQ==","OCR_WORKER_URL":"aHR0cDovL29jci13b3JrZXI6ODAwMQ==","PADDLEOCR_LANG":"ZW4sYXI=","POSTGRES_DB":"Y3VzdG9tZXJsbG0=","POSTGRES_PASSWORD":"Y2hhbmdlbWVfc2VjdXJlX3Bhc3N3b3Jk","POSTGRES_USER":"Y3VzdG9tZXJsbG0=","QDRANT_API_KEY":"","QDRANT_COLLECTION_NAME":"ZG9jdW1lbnRz","QDRANT_URL":"aHR0cDovL3FkcmFudDo2MzMz","REDIS_URL":"cmVkaXM6Ly9yZWRpczo2Mzc5LzA=","SECRET_KEY":"Y2hhbmdlbWVfZ2VuZXJhdGVfc2VjdXJlX3JhbmRvbV9rZXlfaGVyZV9taW5fMzJfY2hhcnM=","SEED_ADMIN_EMAIL":"YWRtaW5AZXhhbXBsZS5jb20=","SEED_ADMIN_FULL_NAME":"QWRtaW4gVXNlcg==","SEED_ADMIN_PASSWORD":"YWRtaW4xMjM0NTY=","SEED_ADMIN_USERNAME":"YWRtaW4=","SEED_USERS":"dHJ1ZQ==","SEED_USER_EMAIL":"dXNlckBleGFtcGxlLmNvbQ==","SEED_USER_FULL_NAME":"RGVtbyBVc2Vy","SEED_USER_PASSWORD":"dXNlcjEyMzQ1Ng==","SEED_USER_USERNAME":"dXNlcg==","STORAGE_MODE":"cHZj","TEI_API_TOKEN":"","TEI_BASE_URL":"aHR0cDovL3RlaTo4MDgw","TEI_TIMEOUT":"MTIw","VITE_API_URL":"aHR0cHM6Ly9jdXN0b21lcmxsbS1iYWNrZW5kLXNjYWxvdmF0ZS1xcHAtcmVkaGF0LXBvYy5hcHBzLmNsdXN0ZXItNHp4cWIuNHp4cWIuc2FuZGJveDEzNC5vcGVudGxjLmNvbQ==","VITE_GRAFANA_URL":"","VITE_PROMETHEUS_URL":"","VITE_QDRANT_URL":"","VITE_WS_URL":"d3NzOi8vY3VzdG9tZXJsbG0tYmFja2VuZC1zY2Fsb3ZhdGUtcXBwLXJlZGhhdC1wb2MuYXBwcy5jbHVzdGVyLTR6eHFiLjR6eHFiLnNhbmRib3gxMzQub3BlbnRsYy5jb20=","VLLM_API_TOKEN":"","VLLM_BASE_URL":"aHR0cHM6Ly9sbGFtYS0zMS04Yi1pbnN0LXByZWRpY3Rvci5sbGFtYS1tb2RlbC5zdmMuY2x1c3Rlci5sb2NhbDo4NDQz","VLLM_EMBEDDING_BASE_URL":"","VLLM_EMBEDDING_MODEL":"","VLLM_HEALTHCHECK_ENABLED":"dHJ1ZQ==","VLLM_HEALTHCHECK_STRICT":"ZmFsc2U=","VLLM_MODEL":"bGxhbWEtMzEtOGItaW5zdA==","VLLM_TEMPERATURE":"MC4y","VLLM_TIMEOUT":"MzAw","VLLM_TLS_VERIFY":"ZmFsc2U="},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"customerllm-env","namespace":"scalovate-qpp-redhat-poc"}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: "2026-01-14T11:48:54Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:data":
          "f:VLLM_TEMPERATURE": {}
          "f:EMBEDDINGS_PROVIDER": {}
          "f:BACKEND_PORT": {}
          "f:SEED_ADMIN_USERNAME": {}
          "f:VITE_PROMETHEUS_URL": {}
          "f:SEED_USER_FULL_NAME": {}
          "f:SEED_USER_EMAIL": {}
          "f:OCR_WORKER_URL": {}
          "f:VITE_API_URL": {}
          "f:SECRET_KEY": {}
          "f:SEED_ADMIN_PASSWORD": {}
          "f:TEI_TIMEOUT": {}
          "f:OCR_LLM_CORRECTION_ENABLED": {}
          "f:BACKEND_HOST": {}
          "f:QDRANT_COLLECTION_NAME": {}
          "f:QDRANT_URL": {}
          "f:VLLM_EMBEDDING_MODEL": {}
          "f:VITE_GRAFANA_URL": {}
          "f:VLLM_TIMEOUT": {}
          "f:POSTGRES_PASSWORD": {}
          "f:PADDLEOCR_LANG": {}
          "f:OCR_WORKER_PORT": {}
          .: {}
          "f:SEED_USERS": {}
          "f:CORS_ORIGINS": {}
          "f:SEED_USER_USERNAME": {}
          "f:VLLM_HEALTHCHECK_STRICT": {}
          "f:POSTGRES_DB": {}
          "f:BACKEND_URL": {}
          "f:SEED_ADMIN_FULL_NAME": {}
          "f:VLLM_TLS_VERIFY": {}
          "f:SEED_ADMIN_EMAIL": {}
          "f:VITE_WS_URL": {}
          "f:SEED_USER_PASSWORD": {}
          "f:FRONTEND_URL": {}
          "f:REDIS_URL": {}
          "f:QDRANT_API_KEY": {}
          "f:FILE_STORAGE_PATH": {}
          "f:TEI_API_TOKEN": {}
          "f:VLLM_HEALTHCHECK_ENABLED": {}
          "f:APP_ENV": {}
          "f:STORAGE_MODE": {}
          "f:TEI_BASE_URL": {}
          "f:POSTGRES_USER": {}
          "f:VLLM_EMBEDDING_BASE_URL": {}
          "f:APP_NAME": {}
          "f:VITE_QDRANT_URL": {}
          "f:DEBUG": {}
          "f:API_VERSION": {}
          "f:DATABASE_URL": {}
        "f:metadata":
          "f:annotations":
            .: {}
            "f:kubectl.kubernetes.io/last-applied-configuration": {}
        "f:type": {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: "2026-01-14T11:50:23Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:data":
          "f:VLLM_API_TOKEN": {}
          "f:VLLM_BASE_URL": {}
          "f:VLLM_MODEL": {}
data:
  POSTGRES_PASSWORD: Y2hhbmdlbWVfc2VjdXJlX3Bhc3N3b3Jk
  OCR_WORKER_PORT: ODAwMQ==
  SEED_USER_PASSWORD: dXNlcjEyMzQ1Ng==
  VLLM_MODEL: bGxhbWEtMzEtOGItaW5zdA==
  FRONTEND_URL: aHR0cHM6Ly9jdXN0b21lcmxsbS1mcm9udGVuZC1zY2Fsb3ZhdGUtcXBwLXJlZGhhdC1wb2MuYXBwcy5jbHVzdGVyLTR6eHFiLjR6eHFiLnNhbmRib3gxMzQub3BlbnRsYy5jb20=
  QDRANT_API_KEY: ""
  VLLM_HEALTHCHECK_STRICT: ZmFsc2U=
  BACKEND_URL: aHR0cHM6Ly9jdXN0b21lcmxsbS1iYWNrZW5kLXNjYWxvdmF0ZS1xcHAtcmVkaGF0LXBvYy5hcHBzLmNsdXN0ZXItNHp4cWIuNHp4cWIuc2FuZGJveDEzNC5vcGVudGxjLmNvbQ==
  POSTGRES_DB: Y3VzdG9tZXJsbG0=
  VLLM_TLS_VERIFY: ZmFsc2U=
  VLLM_HEALTHCHECK_ENABLED: dHJ1ZQ==
  STORAGE_MODE: cHZj
  VITE_WS_URL: d3NzOi8vY3VzdG9tZXJsbG0tYmFja2VuZC1zY2Fsb3ZhdGUtcXBwLXJlZGhhdC1wb2MuYXBwcy5jbHVzdGVyLTR6eHFiLjR6eHFiLnNhbmRib3gxMzQub3BlbnRsYy5jb20=
  TEI_BASE_URL: aHR0cDovL3RlaTo4MDgw
  APP_NAME: Q3VzdG9tZXJMTE0=
  VLLM_BASE_URL: aHR0cHM6Ly9sbGFtYS0zMS04Yi1pbnN0LXByZWRpY3Rvci5sbGFtYS1tb2RlbC5zdmMuY2x1c3Rlci5sb2NhbDo4NDQz
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  DATABASE_URL: cG9zdGdyZXNxbDovL2N1c3RvbWVybGxtOmNoYW5nZW1lX3NlY3VyZV9wYXNzd29yZEBwb3N0Z3Jlczo1NDMyL2N1c3RvbWVybGxt
  FILE_STORAGE_PATH: L2RhdGE=
  BACKEND_PORT: ODAwMA==
  VLLM_TEMPERATURE: MC4y
  #change token
  VLLM_API_TOKEN: ""
  TEI_API_TOKEN: ""
  VITE_API_URL: aHR0cHM6Ly9jdXN0b21lcmxsbS1iYWNrZW5kLXNjYWxvdmF0ZS1xcHAtcmVkaGF0LXBvYy5hcHBzLmNsdXN0ZXItNHp4cWIuNHp4cWIuc2FuZGJveDEzNC5vcGVudGxjLmNvbQ==
  APP_ENV: cHJvZHVjdGlvbg==
  OCR_WORKER_URL: aHR0cDovL29jci13b3JrZXI6ODAwMQ==
  SECRET_KEY: Y2hhbmdlbWVfZ2VuZXJhdGVfc2VjdXJlX3JhbmRvbV9rZXlfaGVyZV9taW5fMzJfY2hhcnM=
  POSTGRES_USER: Y3VzdG9tZXJsbG0=
  VLLM_EMBEDDING_BASE_URL: ""
  VITE_QDRANT_URL: ""
  BACKEND_HOST: MC4wLjAuMA==
  DEBUG: ZmFsc2U=
  OCR_LLM_CORRECTION_ENABLED: dHJ1ZQ==
  API_VERSION: djE=
  EMBEDDINGS_PROVIDER: dGVp
  SEED_ADMIN_USERNAME: YWRtaW4=
  VITE_PROMETHEUS_URL: ""
  QDRANT_COLLECTION_NAME: ZG9jdW1lbnRz
  SEED_USER_FULL_NAME: RGVtbyBVc2Vy
  SEED_USER_EMAIL: dXNlckBleGFtcGxlLmNvbQ==
  QDRANT_URL: aHR0cDovL3FkcmFudDo2MzMz
  VITE_GRAFANA_URL: ""
  SEED_ADMIN_PASSWORD: YWRtaW4xMjM0NTY=
  PADDLEOCR_LANG: ZW4sYXI=
  VLLM_EMBEDDING_MODEL: ""
  VLLM_TIMEOUT: MzAw
  SEED_USERS: dHJ1ZQ==
  TEI_TIMEOUT: MTIw
  CORS_ORIGINS: aHR0cHM6Ly9jdXN0b21lcmxsbS1mcm9udGVuZC1zY2Fsb3ZhdGUtcXBwLXJlZGhhdC1wb2MuYXBwcy5jbHVzdGVyLTR6eHFiLjR6eHFiLnNhbmRib3gxMzQub3BlbnRsYy5jb20=
  SEED_USER_USERNAME: dXNlcg==
  SEED_ADMIN_FULL_NAME: QWRtaW4gVXNlcg==
  SEED_ADMIN_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
type: Opaque
