apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: qdrant-data
spec:
  acessModes:
    - ReadWriteOnce
  storageClassName: genai-sc
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      securityContext:
        fsGroup: 1001080000
        fsGroupChangePolicy: Always
      containers:
        - name: qdrant
          image: imageregistry.pp.gov.qa/mirror/qdrant/qdrant:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: QDRANT__STORAGE__SNAPSHOTS__TEMP_PATH
              value: /tmp/qdrant-snapshots
            - name: QDRANT__STORAGE__SNAPSHOTS__PATH
              value: /tmp/qdrant-snapshots-path
          ports:
            - name: http
              containerPort: 6333
            - name: grpc
              containerPort: 6334
          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage
            - name: qdrant-tmp
              mountPath: /tmp
            - name: qdrant-snapshots
              mountPath: /qdrant/snapshots
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      volumes:
        - name: qdrant-data
          PersistantVolumeClaim:
            claimName: qdrant-data
        - name: qdrant-tmp
          emptyDir: {}
        - name: qdrant-snapshots
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
spec:
  selector:
    app: qdrant
  port:
    - name: http
      port: 6333
      targetPort: http
    - name: grpc
      port: 6334
      targetPort: grpc
